"""
visualize_corpus.py
━━━━━━━━━━━━━━━━━━
Explore and visualize the synthetic observability corpus
generated by generate_observability_corpus.py.

Run after generating the corpus:

    uv run python visualize_corpus.py

Outputs:
  • Terminal summary of corpus statistics
  • Sample sessions (normal, anomalous, cascade)
  • corpus_overview.png  — 4-panel visualization saved to ./

Usage:
    uv run python visualize_corpus.py            # full report + plot
    uv run python visualize_corpus.py --no-plot  # terminal-only
    uv run python visualize_corpus.py --samples  # show 3 sample sessions
"""

import os
import re
import sys
import glob
import argparse
import random
import pyarrow.parquet as pq
import pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec

# ── paths ────────────────────────────────────────────────────────────────────
CACHE_DIR = os.path.join(os.path.expanduser("~"), ".cache", "autoresearch", "data")

# ── helpers ──────────────────────────────────────────────────────────────────

ANOMALY_PATTERNS = re.compile(
    r"error=(?!none)|level=CRITICAL|pagerduty=triggered|policy=VIOLATED|"
    r"health=(?:STALL|VERY_SLOW|ERROR)|reachable=false|alert=true"
)
SOURCE_RE = re.compile(r"\[src=([A-Za-z\-]+)\]")

def classify_session(text: str) -> str:
    """Return 'normal', 'anomalous', or 'cascade' for a session."""
    n_bad = len(ANOMALY_PATTERNS.findall(text))
    if n_bad == 0:
        return "normal"
    if n_bad >= 3:
        return "cascade"
    return "anomalous"

def count_events(text: str) -> int:
    return text.count("[ts=")

def extract_sources(text: str) -> list[str]:
    return SOURCE_RE.findall(text)

def load_shard(path: str) -> list[str]:
    table = pq.read_table(path)
    return table.column("text").to_pylist()


# ── main ─────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(description="Visualize AOMB observability corpus")
    parser.add_argument("--no-plot", action="store_true", help="Skip saving PNG chart")
    parser.add_argument("--samples", action="store_true", help="Print sample sessions")
    parser.add_argument("--shards", type=int, default=None,
                        help="Max shards to load (default: all)")
    args = parser.parse_args()

    # ── discover shards ───────────────────────────────────────────────────────
    shards = sorted(glob.glob(os.path.join(CACHE_DIR, "shard_*.parquet")))
    if not shards:
        print(f"No parquet shards found in {CACHE_DIR}")
        print("Run 'uv run python generate_observability_corpus.py' first.")
        sys.exit(1)

    if args.shards:
        shards = shards[: args.shards]

    print("=" * 70)
    print("  AOMB CORPUS VISUALIZER")
    print("=" * 70)
    print(f"  Found {len(shards)} shards in {CACHE_DIR}")
    total_size_mb = sum(os.path.getsize(s) for s in shards) / 1e6
    print(f"  Total size on disk : {total_size_mb:.1f} MB")
    print()

    # ── load & analyse ────────────────────────────────────────────────────────
    all_sessions = []
    for s in shards:
        all_sessions.extend(load_shard(s))

    print(f"  Total sessions loaded : {len(all_sessions):,}")

    # classify
    labels   = [classify_session(t) for t in all_sessions]
    n_events = [count_events(t)     for t in all_sessions]

    label_counts = {k: labels.count(k) for k in ["normal", "anomalous", "cascade"]}
    total = len(labels)

    # source counts
    src_counts: dict[str, int] = {}
    for t in all_sessions:
        for src in extract_sources(t):
            src_counts[src] = src_counts.get(src, 0) + 1

    # latency extraction (sample from first 2000 sessions for speed)
    latency_normal: list[float] = []
    latency_anomaly: list[float] = []
    lat_re = re.compile(r"latency_ms=(\d+)")
    for text, lbl in zip(all_sessions[:2000], labels[:2000]):
        lats = [int(m) for m in lat_re.findall(text)]
        if lbl == "normal":
            latency_normal.extend(lats)
        else:
            latency_anomaly.extend(lats)

    # ── terminal report ───────────────────────────────────────────────────────
    print()
    print("  Session Distribution")
    print("  ─────────────────────────────────────────────")
    for lbl, cnt in label_counts.items():
        bar = "█" * int(50 * cnt / total)
        pct = 100 * cnt / total
        print(f"  {lbl:<12} {cnt:>6,}  ({pct:5.1f}%)  {bar}")

    print()
    print("  Telemetry Source Mix  (events, not sessions)")
    print("  ─────────────────────────────────────────────")
    src_total = sum(src_counts.values())
    for src, cnt in sorted(src_counts.items(), key=lambda x: -x[1]):
        bar = "█" * int(40 * cnt / src_total)
        pct = 100 * cnt / src_total
        print(f"  {src:<20} {cnt:>8,}  ({pct:5.1f}%)  {bar}")

    print()
    print("  Session Length (events per session)")
    print("  ─────────────────────────────────────────────")
    ev_series = pd.Series(n_events)
    print(f"  min={ev_series.min()}  p25={ev_series.quantile(.25):.0f}  "
          f"median={ev_series.median():.0f}  p75={ev_series.quantile(.75):.0f}  "
          f"max={ev_series.max()}")

    # ── sample sessions ───────────────────────────────────────────────────────
    if args.samples:
        print()
        print("=" * 70)
        print("  SAMPLE SESSIONS")
        print("=" * 70)
        random.seed(42)

        for want in ["normal", "anomalous", "cascade"]:
            pool = [t for t, l in zip(all_sessions, labels) if l == want]
            if not pool:
                continue
            sample = random.choice(pool)
            lines = sample.strip().split("\n")
            print()
            print(f"  ── {want.upper()} SESSION ({len(lines)} events) ──")
            for line in lines[:8]:         # show at most 8 lines
                print("  " + line[:100])
            if len(lines) > 8:
                print(f"  ... ({len(lines) - 8} more events)")

    # ── plot ───────────────────────────────────────────────────────────────────
    if not args.no_plot:
        fig = plt.figure(figsize=(14, 10))
        fig.suptitle("AOMB Observability Corpus — Overview", fontsize=14, fontweight="bold")
        gs = gridspec.GridSpec(2, 2, figure=fig, hspace=0.4, wspace=0.35)

        # ── 1. session type pie ───────────────────────────────────────────────
        ax1 = fig.add_subplot(gs[0, 0])
        colors = {"normal": "#2ecc71", "anomalous": "#e67e22", "cascade": "#e74c3c"}
        wedge_colors = [colors[k] for k in label_counts]
        ax1.pie(
            list(label_counts.values()),
            labels=[f"{k}\n{v:,}\n({100*v/total:.1f}%)"
                    for k, v in label_counts.items()],
            colors=wedge_colors,
            startangle=90,
            wedgeprops={"edgecolor": "white", "linewidth": 1.5},
        )
        ax1.set_title("Session Types", fontweight="bold")

        # ── 2. source bar chart ───────────────────────────────────────────────
        ax2 = fig.add_subplot(gs[0, 1])
        src_labels = list(src_counts.keys())
        src_vals   = [src_counts[k] for k in src_labels]
        bar_colors = ["#3498db", "#9b59b6", "#1abc9c", "#f39c12", "#e74c3c", "#2ecc71"]
        bars = ax2.barh(src_labels, src_vals, color=bar_colors[: len(src_labels)])
        ax2.set_xlabel("Event count")
        ax2.set_title("Events by Telemetry Source", fontweight="bold")
        for bar, val in zip(bars, src_vals):
            ax2.text(bar.get_width() + max(src_vals) * 0.01,
                     bar.get_y() + bar.get_height() / 2,
                     f"{val:,}", va="center", fontsize=8)
        ax2.set_xlim(0, max(src_vals) * 1.15)

        # ── 3. session length histogram ───────────────────────────────────────
        ax3 = fig.add_subplot(gs[1, 0])
        ax3.hist(n_events, bins=30, color="#3498db", edgecolor="white", linewidth=0.5)
        ax3.axvline(pd.Series(n_events).median(), color="#e74c3c",
                    linestyle="--", linewidth=1.5, label=f"median={pd.Series(n_events).median():.0f}")
        ax3.set_xlabel("Events per session")
        ax3.set_ylabel("Count")
        ax3.set_title("Session Length Distribution", fontweight="bold")
        ax3.legend(fontsize=9)

        # ── 4. latency distribution (log scale) ───────────────────────────────
        ax4 = fig.add_subplot(gs[1, 1])
        if latency_normal:
            ax4.hist(latency_normal, bins=50, alpha=0.6,
                     color="#2ecc71", edgecolor="none", label="normal", log=True)
        if latency_anomaly:
            ax4.hist(latency_anomaly, bins=50, alpha=0.6,
                     color="#e74c3c", edgecolor="none", label="anomalous/cascade", log=True)
        ax4.set_xlabel("latency_ms")
        ax4.set_ylabel("Count (log scale)")
        ax4.set_title("Latency Distribution: Normal vs Anomalous", fontweight="bold")
        ax4.legend(fontsize=9)
        ax4.set_xscale("log")

        out_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "corpus_overview.png")
        plt.savefig(out_path, dpi=130, bbox_inches="tight")
        print()
        print(f"  Plot saved → {out_path}")

    print()
    print("=" * 70)
    print("  QUICK REFERENCE — reading the data yourself")
    print("=" * 70)
    print("""
  import pyarrow.parquet as pq, os

  data_dir = os.path.expanduser("~/.cache/autoresearch/data")

  # Load one shard
  df = pq.read_table(f"{data_dir}/shard_00000.parquet").to_pandas()
  print(df["text"].iloc[0])         # print first session

  # Count events in each session
  df["n_events"] = df["text"].str.count(r"\\[ts=")

  # Filter for anomalous sessions
  anomalous = df[df["text"].str.contains("pagerduty=triggered|policy=VIOLATED")]
  print(f"Anomalous sessions in shard_00000: {len(anomalous)}")
""")


if __name__ == "__main__":
    main()
